/* 4-letter word list for Wordle */
var WORDS_4 = (function () {
    var answers = [
        'THAT','WITH','HAVE','THIS','WILL','YOUR','FROM','THEY','BEEN','CALL',
        'COME','MAKE','FIND','EACH','TELL','DOES','HELP','GIVE','MOST','JUST',
        'OVER','SUCH','TAKE','YEAR','THEM','SOME','TIME','VERY','WHEN','WORK',
        'KNOW','LONG','MADE','LIKE','BACK','ONLY','ALSO','GOOD','LOOK','MANY',
        'THEN','WELL','ALSO','WANT','EVEN','HERE','MUCH','LIFE','GAME','PLAY',
        'HOME','LOVE','HAND','HIGH','LAST','KEEP','LIVE','HOLD','TURN','MOVE',
        'SHOW','SIDE','HEAD','DONE','WORD','BEST','BODY','BOTH','DOOR','EVER',
        'FACE','FEEL','FORM','FULL','HALF','HARD','IDEA','KING','LEFT','LINE',
        'LOST','MIND','MISS','NAME','NEXT','NONE','ONCE','OPEN','PAID','PART',
        'PAST','PICK','PLAN','PULL','PUSH','READ','REAL','RICH','ROAD','ROCK',
        'ROLE','ROOM','RULE','SAFE','SAID','SAME','SEEN','SELF','SENT','SHIP',
        'SHUT','SIGN','SING','SIZE','SKIN','SLOW','SNAP','SOFT','SOLD','SONG',
        'SORT','SOUL','STAR','STAY','STEP','STOP','SURE','TALK','TEAM','THAN',
        'THIN','THUS','TILL','TOLD','TONE','TOOK','TOOL','TOWN','TREE','TRIP',
        'TRUE','TYPE','UNIT','UPON','USED','USER','VAST','VIEW','VOTE','WAIT',
        'WAKE','WALK','WALL','WARM','WARN','WASH','WAVE','WEAK','WEAR','WEEK',
        'WENT','WERE','WEST','WHAT','WHOM','WIDE','WIFE','WILD','WIND','WINE',
        'WISH','WOOD','WORE','WRAP','YARD','ZERO','ZONE','ABLE','ACRE','AGED',
        'ARMY','AUNT','BABE','BAND','BANG','BANK','BARE','BARN','BASE','BATH',
        'BEAD','BEAM','BEAN','BEAR','BEAT','BEEF','BEER','BELL','BELT','BEND'
    ];

    var extra = [
        'BIKE','BILL','BIND','BIRD','BITE','BLOW','BLUE','BLUR','BOAT','BOLD',
        'BOLT','BOMB','BOND','BONE','BOOK','BOOM','BOOT','BORE','BORN','BOSS',
        'BOWL','BRED','BREW','BULK','BULL','BURN','BURY','BUSY','BYTE','CAFE',
        'CAGE','CAKE','CALM','CAME','CAMP','CAPE','CARD','CARE','CART','CASE',
        'CASH','CAST','CAVE','CELL','CHAT','CHEF','CHIN','CHIP','CHOP','CITE',
        'CITY','CLAD','CLAM','CLAP','CLAY','CLIP','CLUE','COAL','COAT','CODE',
        'COIL','COIN','COLD','COPE','COPY','CORD','CORE','CORN','COST','COUP',
        'CRAB','CREW','CROP','CROW','CUBE','CULT','CUPS','CURB','CURE','CURL',
        'CUTE','DAMN','DARE','DARK','DART','DASH','DATA','DATE','DAWN','DEAD',
        'DEAF','DEAL','DEAR','DEBT','DECK','DEED','DEEM','DEEP','DEER','DEMO',
        'DENY','DESK','DIAL','DICE','DIED','DIET','DIME','DINE','DIRT','DISC',
        'DISH','DOCK','DOLL','DOME','DOSE','DOWN','DRAG','DRAW','DREW','DROP',
        'DRUM','DUAL','DUCK','DUDE','DUEL','DUMB','DUMP','DUNE','DUSK','DUST',
        'DUTY','DYED','EACH','EARN','EASE','EAST','EASY','EDGE','EDIT','EGGS',
        'ELSE','EMIT','ENVY','EPIC','EURO','EXAM','EXEC','EXIT','EXPO','EYED',
        'EYES','FACT','FADE','FAIL','FAIR','FAKE','FALL','FAME','FANG','FARE',
        'FARM','FAST','FATE','FAWN','FEAR','FEAT','FEED','FELL','FELT','FILE',
        'FILL','FILM','FINE','FIRE','FIRM','FISH','FIST','FLAG','FLAT','FLAW',
        'FLED','FLEW','FLIP','FLOG','FLOW','FOAM','FOIL','FOLD','FOLK','FOND',
        'FONT','FOOL','FOOT','FORD','FORK','FORT','FOUL','FOUR','FREE','FROM',
        'FUEL','FUND','FURY','FUSE','FUSS','GAIN','GALE','GANG','GASH','GATE',
        'GAVE','GAZE','GEAR','GENE','GIFT','GILD','GIRL','GLAD','GLEN','GLOW',
        'GLUE','GOAT','GOES','GOLD','GOLF','GONE','GOWN','GRAB','GRAM','GRAY',
        'GREW','GREY','GRID','GRIM','GRIN','GRIP','GROW','GULF','GURU','GUST',
        'GUTS','GUYS','HACK','HAIL','HAIR','HALE','HALT','HANG','HARE','HARM',
        'HARP','HASH','HATE','HAUL','HAWK','HAZE','HEAP','HEAR','HEAT','HEEL',
        'HEIR','HELM','HERB','HERD','HERO','HIDE','HIKE','HILL','HINT','HIRE',
        'HISS','HITS','HIVE','HOLD','HOLE','HOLY','HOOD','HOOK','HOPE','HORN',
        'HOST','HOUR','HUGE','HULL','HUNG','HUNT','HURT','HYMN','ICON','IDLE',
        'INCH','INFO','IRON','ISLE','ITEM','JACK','JADE','JAIL','JAZZ','JEAN',
        'JERK','JEST','JOBS','JOIN','JOKE','JOLT','JUMP','JUNE','JURY','KEEN',
        'KELP','KEPT','KICK','KIDS','KILL','KIND','KISS','KITE','KNEE','KNEW',
        'KNIT','KNOB','KNOT','LACE','LACK','LAID','LAKE','LAMB','LAME','LAMP',
        'LAND','LANE','LAPS','LARD','LARK','LASH','LATE','LAWN','LAWS','LAZY',
        'LEAD','LEAF','LEAK','LEAN','LEAP','LEND','LENS','LIED','LIEU','LIFT',
        'LIMB','LIME','LIMP','LINK','LION','LIPS','LIST','LOAD','LOAF','LOAN',
        'LOCK','LOFT','LOGO','LONE','LOOP','LORD','LORE','LOTS','LOUD','LUCK',
        'LUMP','LUNG','LURE','LURK','LUSH','MACE','MAIL','MAIN','MALE','MALL',
        'MALT','MANE','MAPS','MARE','MARK','MARS','MASH','MASK','MASS','MAST',
        'MATE','MATH','MAZE','MEAL','MEAN','MEAT','MELT','MEMO','MEND','MENU',
        'MESH','MESS','MILD','MILE','MILK','MILL','MINE','MINT','MIST','MOAN',
        'MOAT','MOCK','MODE','MOLD','MOLE','MONK','MOOD','MOON','MOOR','MOPE',
        'MOSS','MOTH','MULE','MUSE','MUST','MYTH','NAIL','NAVY','NEAR','NEAT',
        'NECK','NEED','NEST','NEWS','NICE','NODE','NORM','NOSE','NOTE','NOUN',
        'NUDE','NUMB','NUTS','OATH','OBEY','ODDS','OKAY','OMEN','OMIT','ORAL',
        'OURS','OUST','OVEN','OWED','OWNS','PACE','PACK','PAGE','PAIL','PAIN',
        'PAIR','PALE','PALM','PANE','PAPA','PARK','PATH','PAVE','PEAK','PEAL',
        'PEAR','PEAT','PEEL','PEER','PELT','PEST','PILE','PINE','PINK','PIPE',
        'PITY','PLOT','PLOW','PLOY','PLUG','PLUM','PLUS','POEM','POET','POLE',
        'POLL','POLO','POND','PONY','POOL','POPE','PORK','PORT','POSE','POST',
        'POUR','PRAY','PREY','PROP','PROW','PUFF','PUMP','PUNK','PURE','PUTS',
        'QUIZ','RACE','RACK','RAFT','RAGE','RAID','RAIL','RAIN','RAKE','RAMP',
        'RANG','RANK','RANT','RARE','RASH','RATE','RAVE','RAYS','REEF','REEL',
        'RELY','RENT','REST','RICE','RIDE','RIFT','RIND','RING','RIOT','RIPE',
        'RISE','RISK','RITE','ROAM','ROAR','ROBE','RODE','ROLL','ROOF','ROOT',
        'ROPE','ROSE','ROTE','ROUT','RUDE','RUIN','RUMP','RUNG','RUSH','RUST',
        'SACK','SAGE','SAKE','SALE','SALT','SAND','SANE','SANK','SEAL','SEAM',
        'SEAT','SECT','SEED','SEEK','SEEM','SEER','SHED','SHIN','SHOP','SHOT',
        'SILK','SILL','SILO','SILT','SINK','SITE','SLAB','SLAG','SLAM','SLAP',
        'SLID','SLIM','SLIP','SLIT','SLOT','SLUG','SMOG','SNAP','SNOB','SNOW',
        'SOAK','SOAP','SOAR','SOCK','SODA','SOFA','SOIL','SOLE','SOME','SORE',
        'SPAN','SPAR','SPEC','SPED','SPIN','SPIT','SPOT','SPUR','STAB','STAG',
        'STEM','STEW','STIR','STUB','STUD','STUN','SUCK','SUIT','SULK','SUMP',
        'SUNG','SUNK','SURF','SWAN','SWAP','SWIM','TABS','TACK','TACT','TAIL',
        'TALE','TALL','TAME','TANK','TAPE','TAPS','TASK','TEAR','TEEM','TEMP',
        'TEND','TENT','TERM','TEST','TEXT','TIDE','TIDY','TIED','TIER','TILE',
        'TILT','TINY','TIRE','TOAD','TOLL','TOMB','TORE','TORN','TORT','TOSS',
        'TOUR','TRAM','TRAP','TRAY','TRIM','TRIO','TROT','TUCK','TUBE','TUNA',
        'TUNE','TURF','TWIN','URGE','VAIN','VALE','VANE','VARY','VEIL','VEIN',
        'VENT','VERB','VEST','VETO','VIAL','VICE','VINE','VOID','VOLT','WADE',
        'WAGE','WAIL','WASP','WATT','WEED','WEEP','WELD','WEPT','WHIM','WHIP',
        'WICK','WILT','WILY','WINK','WIPE','WIRE','WISE','WITS','WOKE','WOLF',
        'WOMB','WONT','WOOL','WORM','WORN','WOVE','YAWN','YELL','YOGA','YOKE'
    ];

    var all = answers.concat(extra);
    var validSet = new Set();
    for (var i = 0; i < all.length; i++) {
        var w = all[i].trim();
        if (w.length === 4) validSet.add(w);
    }

    return { answers: answers, valid: validSet };
})();
